stages:
    - build


build-docker:
    # Have a docker in docker client
    image: docker:20.10.17
    stage: build
    
    # Load other services, such as databases or dockers, will be 
    # available in your image.  
    services: 
        - docker:20.10.17-dind # dind = docker in docker

    script:
        # pass the VERSION variable to your container (see Dockerfile)
        - docker build -t $CI_REGISTRY_IMAGE/python-poetry:3.10 --build-arg VERSION=3.10 .

    tags:
        - docker
