
# Travis CI configuration file for building ESMF docker images based
# on ubuntu
# 
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum hereon
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileContributor Carsten Lemmen <carsten.lemmen@hereon.de

language: generic
dist: jammy
services:
  - docker

sudo: true

git:
  depth: 1
  quiet: true

env:
  VERSION: v8.4.0

  matrix:
    - COMMUNICATOR=openmpi
    - COMMUNICATOR=mpich

before_install:
  - sudo -E apt-get -yq update && \
    sudo -E apt-get -yq --no-install-suggests --no-install-recommends  \
    lib${COMMUNICATOR}-dev make \
    cmake wget python3 python3-pip \
    python-is-python3 libmetis-dev libnetcdf-dev \
    libnetcdff-dev libxerces-c-dev liblapack-dev libyaml-cpp-dev \
    libparmetis-dev subversion cvs git
  - if [ "x${COMMUNICATOR}" != "xmpich" ] ; then apt-get remove -qy *mpich* ; fi
  - if [ "x${COMMUNICATOR}" != "xopenmpi" ] ; then apt-get remove -qy *openmpi* ; fi

install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install

before_script:
#  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
  - poetry run reuse lint
#  - docker build -t "$CONTAINER_REGISTRY_IMAGE" --build-arg VERSION="$VERSION" --build-arg COMMUNICATOR="$COMMUNICATOR" .
#  - docker push "$CONTAINER_REGISTRY_IMAGE"

after_success: 
cache:
  apt: true
  directories:
  - $HOME/travis
